=== Sonatype: add required elements in pom.xml
[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	...
	<groupId>com.github.justcoke</groupId> //<1>
	<artifactId>demo</artifactId> //<2>
	<version>1.0</version> //<3>
	...
	<name>Demo Application</name> //<4>
	<description>Artifact's description</description> //<5>
	<url>http://www.example.com/example-application</url> //<6>
	...
	<licenses> //<7>
		<license>
			<name>Apache 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	...
	<developers> //<8>
		<developer>
			<name>Björn Engel</name>
			<url>http://about.me/bjoernengel</url>
			<timezone>Europe/Berlin</timezone>
		</developer>
	</developers>
	...
	<scm> //<9>
		<developerConnection>scm:git:git@github.com:justcoke/properties-maven-plugin.git</developerConnection>
		<connection>scm:git:https://github.com/justcoke/properties-maven-plugin.git</connection>
		<url>https://github.com/justcoke/properties-maven-plugin.git</url>
	  <tag>HEAD</tag>
   </scm>
	...
	<!-- configure Maven to deploy to the OSSRH Nexus server with the Nexus
		Staging Maven plugin -->
	<distributionManagement> //<10>
		<!-- the Maven deploy plugin needs a full distributionManagement section -->
		<repository>
			<id>ossrh-release</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
			<uniqueVersion>true</uniqueVersion>
		</repository>
		<snapshotRepository>
			<id>ossrh-snapshot</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<uniqueVersion>false</uniqueVersion>
		</snapshotRepository>
		<!-- The above configurations will get the user account details to deploy
			to OSSRH from Maven settings.xml file. -->
	</distributionManagement>
	...
	<build>
		<plugins>
			<plugin> //<11>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.5.3</version>
				<configuration>
					<autoVersionSubmodules>true</autoVersionSubmodules>
					<releaseProfiles>release</releaseProfiles> //<12>
				</configuration>
			</plugin>
		</plugins>
		...
	</build>

	<profiles>
		<profile>
			<id>release</id> //<13>
			<build>
				<plugins>
					<plugin> //<14>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-source-plugin</artifactId>
						<version>2.2.1</version>
						<executions>
							<execution>
								<id>attach-sources</id>
								<goals>
									<goal>jar-no-fork</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin> //<15>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<version>2.9.1</version>
						<executions>
							<execution>
								<id>attach-javadocs</id>
								<goals>
									<goal>jar</goal>
								</goals>
								<configuration>
									<additionalparam>-Xdoclint:none</additionalparam>
									<show>public</show>
									<quiet>true</quiet>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin> //<16>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<version>1.6</version>
						<executions>
							<execution>
								<id>sign-artifacts</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		...
	</profiles>
</project>
----

<1> top level namespace level for your project starting with the reverse domain name
<2> unique name for component
<3> version string for component
<4> project name
<5> project description
<6> project website
<7> license information
<8> developer information
<9> SCM information
<10> distribution management's information
<11> using maven-release-plugin
<12> profile's name for release
<13> profile for release
<14> released artifact's source
<15> released artifact's javadoc
<16> signing released artifact

_http://central.sonatype.org/pages/requirements.html[Requirements]_

=== Updating settings.xml
* add sonatype login data in maven's settings.xml
[source,xml]
----
<server>
    <id>ossrh-release</id>
    <username>your-jira-id</username>
    <password>your-jira-pwd</password>
</server>
----

=== Releasing
[source,bash]
----
$ mvn release:clean release:prepare
----
and
[source,bash]
----
$ mvn release:perform
----

If an error occures run `mvn release:rollback` to revert changes made by prepare-step.

* visit _https://oss.sonatype.org/_ to check uploaded artifact
* **close**
* **release**
* wait

_http://blog.sonatype.com/2009/09/maven-tips-and-tricks-using-github/[Maven Tips and Tricks: Using GitHub]_
_http://central.sonatype.org/pages/releasing-the-deployment.html[Releasing the Deployment]_